### ISSUE TITLE
AttributeError: 'Solver' object has no attribute 'augmentation_prob'

### ISSUE THREAD

**Issue by ghost** [CN-zdy/MSU_Net#5]
Traceback (most recent call last):
  File "train.py", line 119, in <module>
    main(config)
  File "train.py", line 84, in main
    solver.train()
  File "/home/hammad/thyroid/MSU_Net/solver.py", line 218, in train
    self.augmentation_prob, learn_rate])
AttributeError: 'Solver' object has no attribute 'augmentation_prob'

**Comment by CN-zdy** [comment]
Thank you for your interest in our work. This issue has been fixed.

**Comment by CN-zdy** [comment]
If u have no questions, i will close this on July 23.
